sudo: required
services:
  - docker
language: bash
script:
  - make shellcheck
  - VERSION=${TRAVIS_TAG} make sd-image
branches:
  only:
    - master
    - /^v\d.*$/
deploy:
  provider: releases
  api_key:
    secure: "FwtpfzridyXfGdyOm7f1+jbf3EdfnHEO+B3CGaGV4L/noodMCn0qpgbMcAAJkkuqXN1xpSBzkbCx1W/iEEi7WGdI7rVxL93C60T0mzSjH01s4UGRVa7H5dMo73ry8HKQAnvA3fakCnFtjiJpkVGuoq7fJOdjNFw7UWgivzGeps/r/oconsGhooZPnSnpp5LRv55zIRJBAGEB8V2HpbVdCQkXqOUS7lBIypsb53Xew/LL5px9SzLnSPr9A7uXcdyE8Jdw0ogU1E5IFAdWvelmmkBBgmKBpdRjDPEvonViaaH/En4NlyG3H4+Mk5sZpfEjhyWhunOdDmDKDS4zqraixW+XtwLQkBI1sAk+/qgaDtEDMxxoHiuHg91xSZr1O+nq9OBs9AkZoNcIjIQnCWe6m5dD2RtvwGeqGub15viWx9AtauaT/qkT/Ma+hXgJScgjOyegppfFDYr1tt0LSTZ/GAf6DhWQkO/WCC6MGoBbNu5aAez/LEMftVXmJ+3nTjf/IIlebndV17b9ca5eMNOhLismSvRQD3QK2n3iKFhA6mGHS898f6gpQzpuMRVdEr0W8BaoPvzieECx6C6fi1SycBP7tCn1iBJXSzcv+XAOpriGXgS4gGAOIwN3DQySCwjS7Tct+qEcwsjakZUWq2TV4qnEBu+3Q0R4u6Ojxu/vlOo="
  file:
    - sd-card-odroid-xu4-${TRAVIS_TAG}.img.zip
  on:
    tags: true
    repo: hypriot/image-builder-odroid-xu4
